### PR TITLE
Code cleanup

### LINKED ISSUE #259: hsfiletypes.determineTBLtype doesn't work properly
**Describe the bug**
Sometimes, while opening .tbl files of type StringTable (string.tbl) the app determinates its type as a font table and runs wrong editor

**To Reproduce**
1.open some project with aux MPQs
2. in mpq explorer go to d2data.mpq/data/local/lng/{come language e.g eng}
3. click on string.tbl
4. sometimes, you can see font table loading error

**Expected behavior**
every time, when you click on `string.tbl` the appropriate editor should be opened

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Fedora release 33 (Thirty Three)

### PR DESCRIPTION
**Pull request by gravestench**
This PR is in general just aiming to increase coherence, make things easier to read by breaking things up, adding comments, fixing typos, removing unnecessary nolints, etc.

### CODE REVIEW

**Comment by gravestench** [comment]
I'm lumping the fix for #259 In here because it is a pretty obvious fix.

File: hswidget/custom_widgets.go [hunk 1]
```diff
@@ -38,7 +38,6 @@ type playPauseButtonState struct {
 
 func (s *playPauseButtonState) Dispose() {
 	s.playTexture = nil
-	s.playTexture = nil
```
Comment (gucio321) [inline hswidget/custom_widgets.go:41]: `s.pauseTexture = nil`

File: hswindow/hstoolwindow/hsmpqexplorer/mpqexplorer.go [hunk 2]
```diff
@@ -117,7 +117,7 @@ func (m *MPQExplorer) GetMpqTreeNodes() []g.Widget {
 		go func(idx int) {
 			mpq, err := d2mpq.FromFile(filepath.Join(m.config.AuxiliaryMpqPath, m.project.AuxiliaryMPQs[idx]))
 			if err != nil {
-				log.Fatal("failed to load mpq: ", err)
+				log.Print("failed to load mpq: ", err)
```
Comment (gucio321) [inline hswindow/hstoolwindow/hsmpqexplorer/mpqexplorer.go]: `mpq` may be nil, so I suggest to return after `log.Print` call

File: hswindow/hstoolwindow/hsprojectexplorer/projectexplorer.go [hunk 3]
```diff
@@ -138,13 +138,21 @@ func (m *ProjectExplorer) GetProjectTreeNodes() g.Layout {
...
 		return []g.Widget{g.Label("No file structure detected...")}
 	}
 
-	return []g.Widget{m.renderNodes(m.project.GetFileStructure())}
+	nodes, err := m.project.GetFileStructure()
+	if err != nil {
+		return []g.Widget{g.Label(err.Error())}
+	}
+
+	return []g.Widget{m.renderNodes(nodes)}
```
Comment (gucio321) [inline hswindow/hstoolwindow/hsprojectexplorer/projectexplorer.go]: why not `g.Layout(m.renderNodes(nodes))`?

File: hswindow/hstoolwindow/hsprojectexplorer/projectexplorer.go [hunk 4]
```diff
@@ -138,13 +138,21 @@ func (m *ProjectExplorer) GetProjectTreeNodes() g.Layout {
 		return []g.Widget{g.Label("No project loaded...")}
 	}
 
-	fileStructure := m.project.GetFileStructure()
+	fileStructure, err := m.project.GetFileStructure()
+	if err != nil {
+		dialog.Message(err.Error()).Error()
+	}
```
Comment (gucio321) [inline hswindow/hstoolwindow/hsprojectexplorer/projectexplorer.go]: why, in cases like that, don't you `log`-`Print` errors?

File: hswidget/custom_widgets.go (hunk 1 above)
Comment (gravestench) [reply hswidget/custom_widgets.go:41]: ah, was wondering about that

File: hswindow/hstoolwindow/hsmpqexplorer/mpqexplorer.go (hunk 2 above)
Comment (gravestench) [reply hswindow/hstoolwindow/hsmpqexplorer/mpqexplorer.go]: this is inside of a go func. I fixed by also checking if mpg is nil before using it.

File: hswindow/hstoolwindow/hsprojectexplorer/projectexplorer.go (hunk 3 above)
Comment (gravestench) [reply hswindow/hstoolwindow/hsprojectexplorer/projectexplorer.go]: good point. I think it's just old code, I kept the style. updating...

File: hswindow/hstoolwindow/hsprojectexplorer/projectexplorer.go (hunk 4 above)
Comment (gravestench) [reply hswindow/hstoolwindow/hsprojectexplorer/projectexplorer.go]: good point, changed.

File: hsapp/app.go [hunk 5]
```diff
@@ -317,7 +252,7 @@ func (a *App) loadProjectFromFile(file string) {
 		return
 	}
 
-	if !project.ValidateAuxiliaryMPQs(a.config) {
+	if err = project.ValidateAuxiliaryMPQs(a.config); err != nil {
 		log.Printf("Error loading mpqs: %v", err)
 		dialog.Message("Could not load project.\nCould not locate one or more auxiliary MPQs!").Title("Load HellSpawner Project Error").Error()
```
Comment (gucio321) [inline hsapp/app.go]: `logErr("Error loading MPQs: %v", err)`

File: hsapp/app.go [hunk 6]
```diff
@@ -357,7 +292,7 @@ func (a *App) toggleMPQExplorer() {
 func (a *App) onProjectPropertiesChanged(project *hsproject.Project) {
 	a.project = project
 	if err := a.project.Save(); err != nil {
-		log.Fatal(err)
+		log.Print(err)
```
Comment (gucio321) [inline hsapp/app.go]: maybe use `logErr` to also print a `dialog` message?

File: hsapp/app.go [hunk 7]
```diff
@@ -377,7 +312,10 @@ func (a *App) onPreferencesChanged(config *hsconfig.Config) {
 }
 
 func (a *App) reloadAuxiliaryMPQs() {
-	a.project.ReloadAuxiliaryMPQs(a.config)
+	if err := a.project.ReloadAuxiliaryMPQs(a.config); err != nil {
+		dialog.Message(err.Error()).Error()
+	}
```
Comment (gucio321) [inline hsapp/app.go]: `logErr("error reloading auxiliary MPQs: %v", err)`

File: hswindow/hseditor/hssoundeditor/soundeditor.go [hunk 8]
```diff
@@ -53,7 +53,8 @@ func Create(_ *hsconfig.Config,
 	data *[]byte, x, y float32, project *hsproject.Project) (hscommon.EditorWindow, error) {
 	streamer, format, err := wav.Decode(bytes.NewReader(*data))
 	if err != nil {
-		log.Fatal(err)
+		log.Print(err)
```
Comment (gucio321) [inline hswindow/hseditor/hssoundeditor/soundeditor.go]: this `log.Print` should be reported by the caller of `Create`. You don't need to put it here.

Comment (gravestench) [reply hswindow/hseditor/hssoundeditor/soundeditor.go]: I didn't put it there, I altered what was there. I was specifically removing all instances of `log.Fatal`.

Comment (gucio321) [reply hswindow/hseditor/hssoundeditor/soundeditor.go]: hmm, right, `log` call was here, but you added `return` statement in a line below, so this log call is not necessary anyway ;-)

Comment (gravestench) [reply hswindow/hseditor/hssoundeditor/soundeditor.go]: That's a good point. I did both of those edits on two different commits, for two different reasons. One commit was to bubble up errors, another commit was to remove instances of `log.Fatal`.

**Review by gucio321 — DISMISSED** [review]
cool!

File: hsapp/flags.go [hunk 9]
```diff
@@ -11,26 +11,75 @@ import (
...
 		flag.PrintDefaults()
 	}
 
 	flag.Parse()
 
-	if *showHelp {
+	if showHelp {
 		flag.Usage()
-		os.Exit(0)
+		os.Exit(0) // this is dangerous, forces us to parse the help flags last
```
Comment (essial) [inline hsapp/flags.go]: Bubble this up and let the caller's caller control the state.

File: hscommon/hsfiletypes/filetype.go [hunk 10]
```diff
@@ -43,31 +43,28 @@ func determineTBLtype(data *[]byte) (FileType, error) {
 		return FileTypeTBLStringTable, nil
 	}
 
-	d := *data
-	if string(d[:4]) == "Woo!" {
+	if string((*data)[:4]) == "Woo!" {
```
Comment (essial) [inline hscommon/hsfiletypes/filetype.go]: Do not de-reference the pointer, this is implicitly done in the condition.

File: hscommon/hsfiletypes/filetype.go [hunk 11]
```diff
@@ -43,31 +43,28 @@ func determineTBLtype(data *[]byte) (FileType, error) {
...
 		return FileTypeTBLFontTable, nil
 	}
 
 	return FileTypeText, nil
 }
 
-func fileExtensionInfo() map[FileType]fileTypeInfoStruct {
-	return map[FileType]fileTypeInfoStruct{
```
Comment (essial) [inline hscommon/hsfiletypes/filetype.go:55]: Make map's key the extension to prevent duplicate extensions in the list.

File: hscommon/hsproject/project.go [hunk 12]
```diff
@@ -250,90 +254,91 @@ func (p *Project) searchPathEntries(pathEntry *hscommon.PathEntry, path string)
...
-	basePath := path.FullPath
-
-	filePathFormat := filepath.Join(basePath, "untitled%d")
-
-	var fileName string
-
-	for i := 0; ; i++ {
-		possibleFileName := fmt.Sprintf(filePathFormat, i)
-		if _, err := os.Stat(possibleFileName); os.IsNotExist(err) {
+func checkIfPathExists(fmtPath string, maxAttempt int) (fileName string, err error) {
```
Comment (essial) [inline hscommon/hsproject/project.go]: getNextUniqueNewPath

File: hscommon/hsproject/project.go [hunk 13]
```diff
@@ -250,90 +254,91 @@ func (p *Project) searchPathEntries(pathEntry *hscommon.PathEntry, path string)
...
+		dialog.Message(err.Error()).Error()
+
+		return err
 	}
 
-	if err := os.Mkdir(fileName, 0o644); err != nil {
-		dialog.Message("Could not create a new project folder!").Error()
+	err = os.Mkdir(fileName, newFileMode)
+	if err != nil {
+		dialog.Message(err.Error()).Error()
```
Comment (essial) [inline hscommon/hsproject/project.go]: Also need to log.

File: hsapp/flags.go (hunk 9 above)
Comment (gravestench) [reply hsapp/flags.go]: Handled this in 170ea91

Also moved `flag.Parse()` out of the `parseHelpArgs` method.

I had to add a private boolean member `app.showUsage`. this is what gets written to when `flag.Parse()` is finally called.

File: hscommon/hsfiletypes/filetype.go (hunk 11 above)
Comment (gravestench) [reply hscommon/hsfiletypes/filetype.go:55]: look at abe7d28

File: hscommon/hsproject/project.go (hunk 12 above)
Comment (gravestench) [reply hscommon/hsproject/project.go]: b4e028a

File: hscommon/hsproject/project.go (hunk 13 above)
Comment (gravestench) [reply hscommon/hsproject/project.go]: 5e2c480

We can clean this up further when we close #309

**Review by essial — APPROVED** [review]
